name: client_app
description: Client Flutter application.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^11.1.0
  flutter_bloc: ^9.1.1
  injectable: ^3.0.0

  #modules
  core: ^0.1.0
  design_system: ^0.1.0
  client_auth: ^0.1.0
  talker_flutter: ^5.1.17
  talker_bloc_logger: ^5.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.5.0
  build_runner: ^2.13.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.2

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true
  assets:
    - config/app_config.json
