targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake

      freezed:
        options:
          to_json: false
          from_json: false
          when: false
          map: false

      injectable_generator:injectable_builder:
        options:
          auto_register: true
          generate_for_injectable: true

      index_generator:
        enabled: true
