targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - unnecessary_null_checks
            - document_ignores

      json_serializable:
        options:
          field_rename: snake

      freezed:
        generate_for:
          - lib/src/features/**/domain/entities/**.dart
          - lib/src/features/**/presentation/blocs/**.dart
        options:
          to_json: false
          from_json: false
          when: false
          map: false

      injectable_generator:injectable_builder:
        options:
          auto_register: true
          generate_for_injectable: true

      flutter_gen_runner:
        options:
          output: lib/gen/
          line_length: 80

      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/src/features/**/presentation/screens/**.dart

      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/src/common/config/router/client_auth_router.dart
