arb-dir: lib/l10n/
template-arb-file: client_auth_en.arb
output-localization-file: client_auth_localizations.dart
output-class: ClientAuthLocalizations
output-dir: lib/gen/l10n
nullable-getter: false
